version: '3.7'
services:
    api:
        depends_on:
            - db
        build: .
        container_name: api
        restart: always
        env_file: .env
        ports:
            - 8080:8080
    db:
        image: mongo:jammy
        container_name: db
        ports:
            - 27017:27017
